### ISSUE TITLE
Create Class Diagram

### ISSUE THREAD

**Issue by AdamT-S** [AdamT-S/Software-Engineering-Coursework#10]

**Comment by unaisq1** [comment]
Uploaded PNG of class diagram to develop branch under the Documentation folder. Available for review.

**Comment by AdamT-S** [comment]
Class diagram is good, but a couple of changes are required. We need a region in the class diagram. I also think that the capital city should just be a variable than a class.

**Comment by MMadejsza** [comment]
+ I moved the current file (05.03 17:43) to the "proper" directory and changed the name accordingly. The source file is missing for the rest of the group.

**Comment by unaisq1** [comment]
Corrected the class diagram. Uploaded the PNG to the develop branch under the Backend folder within Documentation for review

**Comment by AdamT-S** [comment]
Looks good, maybe a slight change in formatting to make it a bit easier to read but other than that its good.
