### ISSUE TITLE
Rework class diagram

### ISSUE THREAD

**Issue by rhaishah** [AdamT-S/Software-Engineering-Coursework#14]
- Add user class
- Add admin class 
- Ensure each class has an ID and a Name
- Use consistent naming conventions e.g. "x code" or "x ID"
- Change population to a method not attribute

**Comment by unaisq1** [comment]
Uploaded PNG to Backend folder under Documentation Folder in Develop Branch. Awaiting review.

**Comment by rhaishah** [comment]
This looks good. The diagram is more clear and uses methods effectively to reduce redundancies.
