### ISSUE TITLE
Create Personas + user stories

### ISSUE THREAD

**Issue by AdamT-S** [AdamT-S/Software-Engineering-Coursework#2]

**Comment by rhaishah** [comment]
**Start Date**: 24/02/2024
**End Date** : 25/02/2024

**Comment by AdamT-S** [comment]
Looks good overall, perhaps could use a bit more detail (I will email over examples used in Computing & Society from last year). Admin persona wanting a secure database might need to be reworked though, as I don't think we are getting taught security in this module, we can try to implement it though. I will discuss in the Sunday review, but it would be good if you can review the work before then.

**Comment by rhaishah** [comment]
Looks good, format is easy to read and is more detailed.
