### ISSUE TITLE
specify fixed schedule

### ISSUE THREAD

**Issue by rhaishah** [AdamT-S/Software-Engineering-Coursework#4]

**Comment by AdamT-S** [comment]
If you can add the files as a .md that would be perfect in the develop branch

**Comment by MMadejsza** [comment]
@Athenaparsa @AdamT-S 
So Wednesday 21:30 -> 22:00? 
+
Sunday 20:00-21:00?

**Comment by AdamT-S** [comment]
Athena can you create a document that states the official meeting times

**Comment by AdamT-S** [comment]
Everything looks good
