### ISSUE TITLE
State Diagram

### ISSUE THREAD

**Issue by AdamT-S** [AdamT-S/Software-Engineering-Coursework#9]

**Comment by MMadejsza** [comment]
@unaisq1 @Athenaparsa @rhaishah @AdamT-S  
feedback pls + resolve the issue :)

**Comment by AdamT-S** [comment]
State Diagram looks good, however the the validation decision should be altered slightly as validated is before not validated. Very small issue but it should be moved around slightly

**Comment by MMadejsza** [comment]
Good point. Corrected.

**Comment by AdamT-S** [comment]
Looks good, no further changes needed.
